sudo: required
services:
  - docker

before_install:
  - docker build -t radim/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true radim/react-test npm test

after_success:
  - docker build -t radim/multi-client ./client
  - docker build -t radim/multi-nginx ./nginx
  - docker build -t radim/multi-server ./server
  - docker build -t radim/multi-worker ./worker
# Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push to Docker hub
  - docker push radim/multi-client
  - docker push radim/multi-nginx
  - docker push radim/multi-server
  - docker push radim/multi-worker


